services:
  - type: web
    name: binary-froster
    env: node
    buildCommand: npm install && npm run build
    startCommand: npm run start
    envVars:
      - key: NODE_ENV
        value: production
      - key: RESEND_API_KEY
        sync: false
      - key: NEXT_PUBLIC_SITE_URL
        sync: false
